hotdog_file_template: '{array}_{freq}_{num_splits}way_{condiment}.txt'

pa4a:
  num_splits: 8

pa4a_dw:
  num_splits: 4

pa4a_dd:
  num_splits: 8

pa4b:
  num_splits: 8

pa4b_dw:
  num_splits: 4

pa4b_dd:
  num_splits: 8

pa5a:
  num_splits: 8

pa5a_dw:
  num_splits: 4

pa5a_dd:
  num_splits: 8

pa5b:
  num_splits: 8

pa5b_dw:
  num_splits: 4

pa5b_dd:
  num_splits: 8

pa6a:
  num_splits: 8

pa6a_dw:
  num_splits: 4

pa6a_dd:
  num_splits: 8

pa6b:
  num_splits: 8

pa6b_dw:
  num_splits: 4

pa6b_dd:
  num_splits: 8

pa7a:
  num_splits: 4

pa7a_dw:
  num_splits: 4

pa7b:
  num_splits: 4

pa7b_dw:
  num_splits: 4